version: '3.1'

services:

  db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/init_test_db.sql:/docker-entrypoint-initdb.d/init-test.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
