version: '3.1'

services:

  db:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5431:5432"
