server:
  port: ${APPLICATION_PORT:9000}
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST_AND_PORT:localhost:5432}/worklog
    username: ${DB_USER:worklog}
    password: ${DB_PWD:worklog-pass}

application:
  domain:
    ${APPLICATION_DOMAIN:http://localhost:9000}
