server:
  port: 9000
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/worklog
    username: worklog
    password: worklog-pass

application:
  domain:
    http://localhost:9000